# Generated by Django 4.0.4 on 2022-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('unique_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('time_slot', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
