# Generated by Django 4.0.4 on 2022-07-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_checker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
        ('AppointmentBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_doctor', to='authentication.doctors'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='assigned_timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_timeslot', to='AppointmentBooking.timeslots'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disease_checker.departments'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppointmentBooking.timeslots'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
