# Generated by Django 4.0.4 on 2022-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('Departments', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('disease', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
