# Generated by Django 4.0.4 on 2022-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='prescription',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
